//auth action types
export const START_AUTH = 'START_AUTH'
export const SUCCESS_AUTH = 'SUCCESS'
export const SUCCESS_UPLOAD = 'SUCCESS_UPLOAD'
export const FAIL_AUTH = 'FAIL_AUTH'
export const LOGOUT_AUTH = 'LOGOUT_AUTH'
export const SET_LOGGED_USER = 'SET_LOGGED_USER'

//product action
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCT = 'GET_PRODUCT'
export const CREATE_PRODUCT_REVIEW = 'CREATE_PRODUCT_REVIEW'

//cart Actions types
export const GET_USER_CART = 'GET_USER_CART'
export const SET_USER_CART = 'SET_USER_CART'
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const ADD_TO_PRODUCT_QUANTITY = 'ADD_TO_PRODUCT_QUANTITY'
export const REMOVE_FROM_PRODUCT_QUANTITY = 'REMOVE_FROM_PRODUCT_QUANTITY'
export const CLEAR_CART = 'CLEAR_CART'

//user action types
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER'
export const UPDATE_CURRENT_USER_SUCCESS = 'UPDATE_CURRENT_USER_SUCCESS'
export const GET_PROFILE = 'GET_PROFILE'
export const PROFILE_LOADING = 'PROFILE_LOADING'
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND'
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE'
export const GET_PROFILES = 'GET_PROFILES'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const GET_ERRORS = 'GET_ERRORS'

//comment acction types
export const GET_COMMENTS = 'GET_COMMENTS'
export const GET_COMMENT = 'GET_COMMENT'
export const ADD_COMMENT = 'ADD_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'

//Search action Types
export const GET_USERS = 'GET_USERS'
export const FAIL_GET_USERS = 'FAIL_GET_USERS'
export const GET_SEARCHED_USER = 'GET_SEARCHED_USER'
export const SET_SEARCHED_USER = 'SET_SEARCHED_USER'
export const FILTER_USERS = 'FILTER_USERS'
export const LOADING_USERS = 'LOADING_USERS'
